workspace:
  base: /shopware/engine/Shopware/Plugins/Local
  path: Backend/SitionSooqr

pipeline:
  test:
    image: dnhsoft/shopware:5.2.22-php7
    commands:
      - /swtools/init.sh
      - php /shopware/bin/console sw:plugin:install SitionSooqr
      - php /shopware/bin/console sw:plugin:activate SitionSooqr
      - php /shopware/bin/console sition:sooqr:xml 1 1

services:
  db:
    image: dnhsoft/mysql-utf8:5.7

