workspace:
  base: /shopware/engine/Shopware/Plugins/Local
  path: Backend/SitionSooqr

matrix:
  IMAGE_VERSION:
    - 5.2.22-php7
    - 5.2.22
    - 5.2.3-php7
    - 5.2.3

services:
  db:
    image: dnhsoft/mysql-utf8:5.7

pipeline:
  test:
    image: dnhsoft/shopware:${IMAGE_VERSION}
    commands:
      - /swtools/init.sh
      - ls -la /shopware/engine/Shopware/Plugins/Local
      - ls -la /shopware/engine/Shopware/Plugins/Local/Backend
      - ls -la /shopware/engine/Shopware/Plugins/Local/Backend/SitionSooqr
      - php /shopware/bin/console sw:plugin:refresh
      - php /shopware/bin/console sw:plugin:install SitionSooqr
      - php /shopware/bin/console sw:plugin:activate SitionSooqr
      - php /shopware/bin/console sition:sooqr:xml 1 1
      - ls -lah tmp/sooqr-1.xml
  
  zip:
    image: dnhsoft/shopware:5.2.22-php7
    when:
      status: success
      # event: tag
      matrix:
        IMAGE_VERSION: 5.2.3
    commands:
      - ./drone-build
      - ls -lah /shopware/engine/Shopware/Plugins/Local

  scp:
    image: appleboy/drone-scp
    pull: true
    when:
      status: success
      # event: tag
      matrix:
        IMAGE_VERSION: 5.2.3
    host: swretailtest.sition-klanten.nl
    secrets: [ 'scp_username', 'scp_password' ]
    target: /home/swretailtest/plugins
    source: /shopware/engine/Shopware/Plugins/Local/*.zip
