#!/usr/bin/env bash

# name of plugin
PLUGINDIR="SitionSooqr"

# save current dir
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# create plugin dir
mkdir -p ~/plugins
cd ~/plugins
mkdir $PLUGINDIR
cd $PLUGINDIR

# get url to git remote
cd "$SCRIPTDIR"
REMOTE_URL=$(git config --get remote.origin.url)
cd ~/plugins/$PLUGINDIR

echo "remote url: $REMOTE_URL"

# clone git repo
git clone $REMOTE_URL .

# # Install composer packages
# composer install --no-dev
# # Make sure autoload map exists
# composer dump-autoload

# remove tests of upperscore library
# echo "Removing tests from upperscore library for Shopware validation - ~/plugins/$PLUGINDIR/vendor/pisc/upperscore/src/tests/*"
# rm ~/plugins/$PLUGINDIR/vendor/pisc/upperscore/src/tests/*

# remove unnecessary files
rm TODO.md
rm ROADMAP.md

rm -rf tests
rm phpunit.xml.dist

rm braceComposer.php
rm generate_zip


# get version from plugin.json
VERSION=$(php -r "echo json_decode(file_get_contents(__DIR__ . '/plugin.json'), true)['currentVersion'];")

cd ..

# zip plugin dir
php ~/public_html/bin/sw plugin:zip:dir ~/plugins/$PLUGINDIR

echo "Renaming $PLUGINDIR.zip to $PLUGINDIR-$VERSION.zip"
mv "$PLUGINDIR.zip" "$PLUGINDIR-$VERSION.zip"

# remove leftover
rm -rf "$PLUGINDIR"

echo " "
echo "~/plugins/$PLUGINDIR-$VERSION.zip"
